let $VIMHOME = expand('<sfile>:p:h')

" Search Text highlight
set hlsearch
" highlight off
nnoremap <silent> <Esc><Esc> :<C-u>nohlsearch<CR><Esc>

let mapleader = "\<Space>"

set encoding=utf-8
set number

" https://qiita.com/Linda_pp/items/9e0c94eb82b18071db34
if has('vim_starting')
    " 挿入モード時に非点滅の縦棒タイプのカーソル
    let &t_SI .= "\e[6 q"
    " ノーマルモード時に非点滅のブロックタイプのカーソル
    let &t_EI .= "\e[2 q"
    " 置換モード時に非点滅の下線タイプのカーソル
    let &t_SR .= "\e[4 q"
endif

" View git diffs with git difftool
" https://stackoverflow.com/questions/890802/how-do-i-disable-the-press-enter-or-type-command-to-continue-prompt-in-vim
map <F5> :wa!<CR>:!git difftool %:p<CR><CR>

" Load Plugin
source $VIMHOME/vim-plug.vim

colorscheme codedark

